# Generated by Django 5.0.2 on 2025-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=255)),
                ('employer_email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
                ('working_mode', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20)),
                ('job_role_and_duties', models.TextField()),
                ('requisite_skill', models.TextField()),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_description_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
