from django.core.management.base import BaseCommand
from job_service.models import Job

class Command(BaseCommand):
    help = 'Populate database with 50 sample job data'

    def handle(self, *args, **options):
        # Sample job data - 50 diverse jobs
        sample_jobs = [
            # Software Development (15 jobs)
            {
                'position': 'Senior Python Developer',
                'workplace': 'TechCorp Solutions',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop and maintain web applications using Python, Django, and React. Lead technical projects and mentor junior developers.',
                'requisite_skill': 'Python, Django, React, PostgreSQL, AWS, Git, Docker',
                'salary_min': 80000,
                'salary_max': 120000,
                'location': 'New York, NY',
            },
            {
                'position': 'Full Stack Developer',
                'workplace': 'WebFlow Technologies',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Build complete web applications from frontend to backend. Work with modern frameworks and cloud technologies.',
                'requisite_skill': 'JavaScript, React, Node.js, MongoDB, Express, AWS, TypeScript',
                'salary_min': 75000,
                'salary_max': 110000,
                'location': 'San Francisco, CA',
            },
            {
                'position': 'Frontend Developer',
                'workplace': 'WebCraft Studios',
                'working_mode': 'remote',
                'job_role_and_duties': 'Create responsive and interactive user interfaces using modern JavaScript frameworks.',
                'requisite_skill': 'JavaScript, React, Vue.js, HTML, CSS, TypeScript, Webpack',
                'salary_min': 70000,
                'salary_max': 100000,
                'location': 'Remote',
            },
            {
                'position': 'Backend Developer',
                'workplace': 'DataSync Systems',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design and implement server-side logic, APIs, and database architecture.',
                'requisite_skill': 'Java, Spring Boot, MySQL, REST APIs, Microservices, Docker',
                'salary_min': 85000,
                'salary_max': 125000,
                'location': 'Austin, TX',
            },
            {
                'position': 'Mobile App Developer',
                'workplace': 'AppWorks Mobile',
                'working_mode': 'contract',
                'job_role_and_duties': 'Develop native and cross-platform mobile applications for iOS and Android.',
                'requisite_skill': 'React Native, Flutter, Swift, Kotlin, Mobile Development',
                'salary_min': 75000,
                'salary_max': 110000,
                'location': 'Miami, FL',
            },
            {
                'position': 'DevOps Engineer',
                'workplace': 'CloudScale Systems',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage cloud infrastructure, implement CI/CD pipelines, and ensure system reliability.',
                'requisite_skill': 'AWS, Docker, Kubernetes, Jenkins, Terraform, Linux, Bash',
                'salary_min': 85000,
                'salary_max': 125000,
                'location': 'Seattle, WA',
            },
            {
                'position': 'Software Engineer',
                'workplace': 'InnovateTech Solutions',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design, develop, and maintain software applications. Collaborate with cross-functional teams.',
                'requisite_skill': 'C++, Python, Git, Agile, Problem Solving, System Design',
                'salary_min': 90000,
                'salary_max': 130000,
                'location': 'Boston, MA',
            },
            {
                'position': 'React Developer',
                'workplace': 'ReactPro Studios',
                'working_mode': 'remote',
                'job_role_and_duties': 'Build modern web applications using React ecosystem. Focus on performance and user experience.',
                'requisite_skill': 'React, Redux, TypeScript, Jest, Webpack, CSS-in-JS',
                'salary_min': 65000,
                'salary_max': 95000,
                'location': 'Remote',
            },
            {
                'position': 'Java Developer',
                'workplace': 'Enterprise Solutions Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop enterprise-level applications using Java technologies and frameworks.',
                'requisite_skill': 'Java, Spring, Hibernate, Maven, JUnit, Microservices',
                'salary_min': 80000,
                'salary_max': 115000,
                'location': 'Chicago, IL',
            },
            {
                'position': 'Python Developer',
                'workplace': 'DataTech Labs',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop Python applications for data processing and automation.',
                'requisite_skill': 'Python, Pandas, NumPy, FastAPI, SQLAlchemy, Testing',
                'salary_min': 70000,
                'salary_max': 105000,
                'location': 'Denver, CO',
            },
            {
                'position': 'UI/UX Developer',
                'workplace': 'DesignFirst Digital',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Create user interfaces and implement design systems with focus on user experience.',
                'requisite_skill': 'HTML, CSS, JavaScript, Figma, Accessibility, Responsive Design',
                'salary_min': 60000,
                'salary_max': 90000,
                'location': 'Portland, OR',
            },
            {
                'position': 'System Administrator',
                'workplace': 'IT Solutions Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage and maintain IT infrastructure, servers, and network systems.',
                'requisite_skill': 'Linux, Windows Server, Networking, Security, Scripting, Monitoring',
                'salary_min': 55000,
                'salary_max': 85000,
                'location': 'Phoenix, AZ',
            },
            {
                'position': 'Database Administrator',
                'workplace': 'DataFlow Systems',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage database systems, optimize performance, and ensure data security.',
                'requisite_skill': 'SQL, PostgreSQL, MySQL, MongoDB, Performance Tuning, Backup',
                'salary_min': 70000,
                'salary_max': 100000,
                'location': 'Atlanta, GA',
            },
            {
                'position': 'Security Engineer',
                'workplace': 'SecureNet Solutions',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Implement security measures, conduct audits, and protect systems from threats.',
                'requisite_skill': 'Cybersecurity, Penetration Testing, SIEM, Firewalls, Compliance',
                'salary_min': 85000,
                'salary_max': 120000,
                'location': 'Washington, DC',
            },
            {
                'position': 'QA Engineer',
                'workplace': 'QualityTech Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design and execute test plans, automate testing, and ensure software quality.',
                'requisite_skill': 'Selenium, JUnit, TestNG, API Testing, Performance Testing, Agile',
                'salary_min': 60000,
                'salary_max': 90000,
                'location': 'Dallas, TX',
            },

            # Data Science & Analytics (10 jobs)
            {
                'position': 'Data Scientist',
                'workplace': 'DataFlow Analytics',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Analyze large datasets, build machine learning models, and provide insights to drive business decisions.',
                'requisite_skill': 'Python, R, SQL, Machine Learning, Statistics, Pandas, Scikit-learn',
                'salary_min': 90000,
                'salary_max': 130000,
                'location': 'San Francisco, CA',
            },
            {
                'position': 'Data Analyst',
                'workplace': 'Insight Analytics',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Analyze data to provide insights and recommendations for business strategy.',
                'requisite_skill': 'SQL, Excel, Tableau, Python, Statistics, Data Visualization',
                'salary_min': 55000,
                'salary_max': 80000,
                'location': 'Nashville, TN',
            },
            {
                'position': 'Machine Learning Engineer',
                'workplace': 'AI Solutions Corp',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Build and deploy machine learning models for production environments.',
                'requisite_skill': 'Python, TensorFlow, PyTorch, MLOps, AWS, Docker',
                'salary_min': 95000,
                'salary_max': 140000,
                'location': 'Seattle, WA',
            },
            {
                'position': 'Business Intelligence Analyst',
                'workplace': 'BI Solutions Ltd',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Create reports and dashboards to support business decision making.',
                'requisite_skill': 'Power BI, Tableau, SQL, Excel, Data Modeling, ETL',
                'salary_min': 65000,
                'salary_max': 95000,
                'location': 'Minneapolis, MN',
            },
            {
                'position': 'Quantitative Analyst',
                'workplace': 'Finance Analytics',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop mathematical models for financial analysis and risk assessment.',
                'requisite_skill': 'Python, R, Statistics, Financial Modeling, Risk Analysis, SQL',
                'salary_min': 80000,
                'salary_max': 120000,
                'location': 'New York, NY',
            },
            {
                'position': 'Data Engineer',
                'workplace': 'DataPipeline Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Build and maintain data pipelines for large-scale data processing.',
                'requisite_skill': 'Python, Apache Spark, Kafka, Airflow, AWS, SQL',
                'salary_min': 85000,
                'salary_max': 125000,
                'location': 'Austin, TX',
            },
            {
                'position': 'Research Analyst',
                'workplace': 'Market Research Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Conduct market research and analyze industry trends and consumer behavior.',
                'requisite_skill': 'Research Methods, SPSS, Excel, Survey Design, Statistical Analysis',
                'salary_min': 50000,
                'salary_max': 75000,
                'location': 'Chicago, IL',
            },
            {
                'position': 'Statistical Analyst',
                'workplace': 'Stats Solutions',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Perform statistical analysis and create predictive models for business insights.',
                'requisite_skill': 'R, SAS, Statistics, Regression Analysis, Hypothesis Testing',
                'salary_min': 60000,
                'salary_max': 90000,
                'location': 'Boston, MA',
            },
            {
                'position': 'Data Visualization Specialist',
                'workplace': 'Visual Data Studio',
                'working_mode': 'remote',
                'job_role_and_duties': 'Create compelling data visualizations and interactive dashboards.',
                'requisite_skill': 'D3.js, Tableau, Power BI, JavaScript, Design Principles',
                'salary_min': 65000,
                'salary_max': 95000,
                'location': 'Remote',
            },
            {
                'position': 'Predictive Analytics Specialist',
                'workplace': 'Future Insights',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop predictive models to forecast trends and business outcomes.',
                'requisite_skill': 'Python, Machine Learning, Time Series Analysis, Forecasting, SQL',
                'salary_min': 75000,
                'salary_max': 110000,
                'location': 'Denver, CO',
            },

            # Design & Creative (8 jobs)
            {
                'position': 'UX/UI Designer',
                'workplace': 'DesignHub Creative',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design user interfaces and experiences for web and mobile applications.',
                'requisite_skill': 'Figma, Adobe Creative Suite, User Research, Prototyping, Wireframing',
                'salary_min': 65000,
                'salary_max': 95000,
                'location': 'Austin, TX',
            },
            {
                'position': 'Graphic Designer',
                'workplace': 'Creative Studio Pro',
                'working_mode': 'freelance',
                'job_role_and_duties': 'Create visual designs for print and digital media including logos, brochures, and social media content.',
                'requisite_skill': 'Adobe Creative Suite, Photoshop, Illustrator, InDesign, Typography',
                'salary_min': 40000,
                'salary_max': 70000,
                'location': 'Los Angeles, CA',
            },
            {
                'position': 'Web Designer',
                'workplace': 'WebDesign Studio',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design and create visually appealing websites with focus on user experience.',
                'requisite_skill': 'HTML, CSS, JavaScript, Photoshop, Responsive Design, UI/UX',
                'salary_min': 55000,
                'salary_max': 85000,
                'location': 'Portland, OR',
            },
            {
                'position': 'Product Designer',
                'workplace': 'Product Design Lab',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design digital products with focus on user experience and business goals.',
                'requisite_skill': 'Figma, Sketch, User Research, Prototyping, Design Systems',
                'salary_min': 70000,
                'salary_max': 105000,
                'location': 'San Francisco, CA',
            },
            {
                'position': 'Motion Graphics Designer',
                'workplace': 'Motion Studio',
                'working_mode': 'contract',
                'job_role_and_duties': 'Create animated graphics and visual effects for video content and presentations.',
                'requisite_skill': 'After Effects, Premiere Pro, Cinema 4D, Animation, Visual Effects',
                'salary_min': 60000,
                'salary_max': 90000,
                'location': 'New York, NY',
            },
            {
                'position': 'Brand Designer',
                'workplace': 'Brand Identity Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop brand identities, logos, and visual guidelines for companies.',
                'requisite_skill': 'Adobe Creative Suite, Brand Strategy, Typography, Color Theory',
                'salary_min': 55000,
                'salary_max': 85000,
                'location': 'Chicago, IL',
            },
            {
                'position': '3D Artist',
                'workplace': '3D Creative Studio',
                'working_mode': 'freelance',
                'job_role_and_duties': 'Create 3D models, animations, and visualizations for various industries.',
                'requisite_skill': 'Blender, Maya, 3ds Max, Texturing, Lighting, Rendering',
                'salary_min': 45000,
                'salary_max': 75000,
                'location': 'Remote',
            },
            {
                'position': 'Illustrator',
                'workplace': 'Art Studio Digital',
                'working_mode': 'freelance',
                'job_role_and_duties': 'Create custom illustrations for books, websites, and marketing materials.',
                'requisite_skill': 'Adobe Illustrator, Procreate, Drawing, Digital Art, Creative Design',
                'salary_min': 35000,
                'salary_max': 65000,
                'location': 'Remote',
            },

            # Marketing & Sales (7 jobs)
            {
                'position': 'Marketing Manager',
                'workplace': 'GrowthFirst Marketing',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop and execute marketing strategies, manage campaigns, and analyze performance metrics.',
                'requisite_skill': 'Digital Marketing, Google Analytics, Social Media, Content Strategy, SEO',
                'salary_min': 60000,
                'salary_max': 90000,
                'location': 'Chicago, IL',
            },
            {
                'position': 'Sales Representative',
                'workplace': 'SalesPro Solutions',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Generate leads, build client relationships, and achieve sales targets.',
                'requisite_skill': 'Sales, CRM, Communication, Negotiation, Customer Service',
                'salary_min': 45000,
                'salary_max': 75000,
                'location': 'Boston, MA',
            },
            {
                'position': 'Digital Marketing Specialist',
                'workplace': 'Digital Marketing Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage digital marketing campaigns across various platforms and channels.',
                'requisite_skill': 'Google Ads, Facebook Ads, SEO, Email Marketing, Analytics',
                'salary_min': 50000,
                'salary_max': 80000,
                'location': 'Miami, FL',
            },
            {
                'position': 'Content Marketing Manager',
                'workplace': 'Content Strategy Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop content strategies and create engaging content for various platforms.',
                'requisite_skill': 'Content Strategy, Copywriting, SEO, Social Media, Analytics',
                'salary_min': 55000,
                'salary_max': 85000,
                'location': 'Austin, TX',
            },
            {
                'position': 'SEO Specialist',
                'workplace': 'Search Engine Pro',
                'working_mode': 'remote',
                'job_role_and_duties': 'Optimize websites for search engines and improve organic traffic.',
                'requisite_skill': 'SEO, Google Analytics, Keyword Research, Technical SEO, Link Building',
                'salary_min': 45000,
                'salary_max': 75000,
                'location': 'Remote',
            },
            {
                'position': 'Social Media Manager',
                'workplace': 'Social Media Studio',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage social media presence and create engaging content for various platforms.',
                'requisite_skill': 'Social Media, Content Creation, Analytics, Community Management, Design',
                'salary_min': 40000,
                'salary_max': 65000,
                'location': 'Los Angeles, CA',
            },
            {
                'position': 'Email Marketing Specialist',
                'workplace': 'Email Marketing Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Design and execute email marketing campaigns to drive engagement and conversions.',
                'requisite_skill': 'Email Marketing, Mailchimp, A/B Testing, Copywriting, Analytics',
                'salary_min': 45000,
                'salary_max': 70000,
                'location': 'Dallas, TX',
            },

            # Business & Management (10 jobs)
            {
                'position': 'Product Manager',
                'workplace': 'InnovateTech',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Define product vision, gather requirements, and work with development teams to deliver products.',
                'requisite_skill': 'Product Management, Agile, User Stories, Market Research, Analytics',
                'salary_min': 95000,
                'salary_max': 140000,
                'location': 'Denver, CO',
            },
            {
                'position': 'Project Manager',
                'workplace': 'Project Solutions Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Lead project teams, manage timelines, budgets, and ensure successful project delivery.',
                'requisite_skill': 'Project Management, Agile, Scrum, Risk Management, Stakeholder Communication',
                'salary_min': 70000,
                'salary_max': 110000,
                'location': 'Phoenix, AZ',
            },
            {
                'position': 'Business Analyst',
                'workplace': 'Business Solutions Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Analyze business processes, gather requirements, and recommend solutions.',
                'requisite_skill': 'Business Analysis, Requirements Gathering, Process Modeling, SQL, Excel',
                'salary_min': 60000,
                'salary_max': 90000,
                'location': 'Atlanta, GA',
            },
            {
                'position': 'Operations Manager',
                'workplace': 'Operations Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Oversee daily operations, manage teams, and optimize business processes.',
                'requisite_skill': 'Operations Management, Process Improvement, Team Leadership, Analytics',
                'salary_min': 65000,
                'salary_max': 100000,
                'location': 'Houston, TX',
            },
            {
                'position': 'Human Resources Manager',
                'workplace': 'HR Solutions Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage HR functions including recruitment, employee relations, and policy development.',
                'requisite_skill': 'HR Management, Recruitment, Employee Relations, HRIS, Compliance',
                'salary_min': 60000,
                'salary_max': 95000,
                'location': 'Nashville, TN',
            },
            {
                'position': 'Financial Analyst',
                'workplace': 'Finance Solutions Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Analyze financial data, create reports, and provide insights for business decisions.',
                'requisite_skill': 'Financial Analysis, Excel, Financial Modeling, Accounting, Budgeting',
                'salary_min': 55000,
                'salary_max': 85000,
                'location': 'Charlotte, NC',
            },
            {
                'position': 'Consultant',
                'workplace': 'Strategic Consulting Group',
                'working_mode': 'contract',
                'job_role_and_duties': 'Provide strategic advice and solutions to clients across various industries.',
                'requisite_skill': 'Consulting, Strategy, Problem Solving, Client Management, Analysis',
                'salary_min': 80000,
                'salary_max': 120000,
                'location': 'Washington, DC',
            },
            {
                'position': 'Account Manager',
                'workplace': 'Client Relations Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Manage client relationships, ensure satisfaction, and drive account growth.',
                'requisite_skill': 'Account Management, Client Relations, Communication, Sales, CRM',
                'salary_min': 50000,
                'salary_max': 80000,
                'location': 'Minneapolis, MN',
            },
            {
                'position': 'Strategy Manager',
                'workplace': 'Strategic Planning Inc',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Develop business strategies, conduct market analysis, and drive organizational growth.',
                'requisite_skill': 'Strategic Planning, Market Analysis, Business Strategy, Competitive Analysis',
                'salary_min': 75000,
                'salary_max': 115000,
                'location': 'Seattle, WA',
            },
            {
                'position': 'Business Development Manager',
                'workplace': 'Business Growth Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Identify new business opportunities, build partnerships, and drive revenue growth.',
                'requisite_skill': 'Business Development, Partnership Building, Sales, Market Research, Networking',
                'salary_min': 65000,
                'salary_max': 100000,
                'location': 'San Diego, CA',
            },
            {
                'position': 'Customer Success Manager',
                'workplace': 'Customer Success Pro',
                'working_mode': 'full_time',
                'job_role_and_duties': 'Ensure customer satisfaction, manage relationships, and drive product adoption.',
                'requisite_skill': 'Customer Success, Relationship Management, Product Knowledge, Communication',
                'salary_min': 55000,
                'salary_max': 85000,
                'location': 'Austin, TX',
            },
        ]

        # Create jobs
        created_count = 0
        for job_data in sample_jobs:
            job, created = Job.objects.get_or_create(
                position=job_data['position'],
                workplace=job_data['workplace'],
                defaults=job_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'Created job: {job.position} at {job.workplace}')
                )

        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} new jobs')
        ) 